Collections:
  - Name: OCSORT
    Metadata:
      Training Techniques:
        - SGD with Momentum
      Training Resources: 8x V100 GPUs
      Architecture:
        - YOLOX
    Paper:
        URL: https://arxiv.org/abs/2203.14360
        Title: Observation-Centric SORT Rethinking SORT for Robust Multi-Object Tracking
    README: configs/mot/ocsort/README.md

Models:
  - Name: ocsort_yolox_x_crowdhuman_mot17-private-half
    In Collection: OCSORT
    Config: configs/mot/ocsort/ocsort_yolox_x_crowdhuman_mot17-private-half.py
    Metadata:
      Training Data: CrowdHuman + MOT17-half-train
    Results:
      - Task: Multiple Object Tracking
        Dataset: MOT17-half-val
        Metrics:
          MOTA: 77.8
          IDF1: 78.4
    Weights: https://download.openmmlab.com/mmtracking/mot/ocsort/mot_dataset/ocsort_yolox_x_crowdhuman_mot17-private-half_20220813_101618-fe150582.pth
